package com.offgrid.android.onboarding

enum class OnboardingState {
    CHECKING,
    PERMISSION_EXPLANATION,
    SET_NICKNAME,
    BLUETOOTH_CHECK,
    LOCATION_CHECK,
    BATTERY_OPTIMIZATION_CHECK,
    BACKGROUND_LOCATION_EXPLANATION,
    PERMISSION_REQUESTING,
    INITIALIZING,
    COMPLETE,
    ERROR
}
